services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: porte_monnaie
      POSTGRES_USER: porte_monnaie
      POSTGRES_PASSWORD: porte_monnaie
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
